version: '3.8'

services:
  frontend:
    build:
      dockerfile: Dockerfile
    container_name: c360_frontend
    ports:
      - "3000:3000"
    networks:
      - consultor360_network

networks:
  consultor360_network:
    external: true